### PR TITLE
Comment spacing and whitespace fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by edwardvmills** [comment]
Hi luzpaz. i like the format, thanks for the PR. i just wrote a bunch of stuff though since my last commit...debugging across many linked functions.

I assume you have an automatic tool for this, would you mind redoing this format after i push the lastest?

I know there's a bunch of git tools to deal with this...but it would probably eat my entire weekend

**Comment by luzpaz** [comment]
@edwardvmills np.. just signal me when when you push the changes and I'll redo the PR

**Comment by edwardvmills** [comment]
awesome, thanks. i have an important general case ready, but now i need to handle all the 0 cases combinations... so many functions are getting touched.

**Comment by edwardvmills** [comment]
ok ready to go on my side. i tried looking at the github web editor to resolve conflicts, but i'm not clear how it works. the conflicts are pretty simple.

it would make my life easier if you just reapplied the format to the  my last commit :)

**Comment by luzpaz** [comment]
@edwardvmills should be good to go :wink:

**Comment by edwardvmills** [comment]
great, thanks

**Pull request merged**
