### PR TITLE
README: Add LGTM badges

### LINKED ISSUE #14: Add LGTM badges
We can also add LGTM analysis per https://github.com/FreeCAD/FreeCAD-addons/issues/163  

[Language grade: Python](https://lgtm.com/projects/g/edwardvmills/Silk/context:python) [Total alerts](https://lgtm.com/projects/g/edwardvmills/Silk/alerts/)

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #14  
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/163

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/Silk/blob/LGTM/README.md

**Comment by edwardvmills** [comment]
when i look at the preview, i see a broken image link.

**Comment by luzpaz** [comment]
@edwardvmills you need to hard refresh to see the badges

**Comment by edwardvmills** [comment]
i'm still not clear on this one. do i need to do more than accept your change to readme.md that adds the banner or not? the LGTM link talks about adding a top level file, and setting up an account somewhere. that seems like too much work for me given how little time i have for the project itself.

If it's just the banner in the readme file, i'm ok with it. but i can't put a whole ton of effort into this just to be told my code is ugly :-) i already know my code is ugly.

**Comment by luzpaz** [comment]
It would be a simple .yml file. that we can use to exlcude certain files from analysis if needed.

**Comment by edwardvmills** [comment]
When i look at your branch, i don't see the "lgtm.yml" file i expect to see at the top level (based on info [here](https://wiki.freecadweb.org/LGTM)). is it there and i'm blind, or did you only include the change to readme.md at this point?

**Comment by luzpaz** [comment]
I didn't add it [`.lgtm.yml`] yet :rofl:   
But i can.

**Comment by luzpaz** [comment]
Closing since LGTM was sunset

**Pull request closed without merging**
