### PR TITLE
README: fix typo

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
bump @edwardvmills

**Comment by edwardvmills** [comment]
Hey Luzpaz. apparently i have been permanently banned from the FreeCAD forum. i am not very clear why. i was in the middle of writing some posts...i didn't think it was anything very controversial.

**Comment by luzpaz** [comment]
Really? lemme check

**Comment by luzpaz** [comment]
crap, did the forum get hacked?!

**Comment by edwardvmills** [comment]
uh oh, did you get locked out too?

**Comment by luzpaz** [comment]
cancel clear...it was an incorrectly applied IP address ban. We're good to go.

**Comment by edwardvmills** [comment]
thanks. i knew the right person to call :)

**Pull request merged**
